MAX_SCORE = 100
MIN_SCORE = 0
INITIAL_SCORE = 5
REDIS_HOST = 'localhost'
REDIS_PASSWD = ''
REDIS_PORT = 6379
REDIS_KEY = 'proxies'
POOL_UPPER_THRESHOLD = 10000

VALID_STATUS_CODES = [200, 302]
TEST_URL = 'http://m.weibo.cn'
BATCH_TEST_SIZE = 100
TEST_TIME_OUT = 6

TESTER_CYCLE = 20
GETTER_CYCLE =  20
TESTER_ENABLED = True
GETTER_ENABLED = True
GETTER_FLAG = 50
GETTER_MAX = 1000
API_ENABLED = True
API_HOST = '127.0.0.1'
API_PORT = 5000

